#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# Border/gap settings
bspc config border_width 				2
bspc config window_gap					15
bspc config split_ratio                 0.50
bspc config single_monocle				true
bspc config borderless_monocle          true
bspc config gapless_monocle				true

bspc config normal_border_color			"#1d2021"
bspc config focused_border_color		"#a89984"

# Mouse settings
bspc config pointer_modifier			shift
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

# Monitor settings
bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true

# Padding setting
bspc config top_padding 				24

# Pointer settings
bspc config focus_follows_pointer 		true

# Program rules
bspc rule -a Gimp desktop=^5 follow=off focus=off
bspc rule -a Zathura state=tiled
