#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# Border/gap settings
bspc config border_width					2
bspc config window_gap						15
bspc config split_ratio						0.50
bspc config single_monocle					true
bspc config borderless_monocle				true
bspc config gapless_monocle					true

bspc config normal_border_color				"#665c54"
bspc config focused_border_color			"#83a598"

# Padding settings
bspc config top_padding						40
bspc config right_padding					15
bspc config left_padding					15
bspc config bottom_padding					15

bspc config top_monocle_padding				-15
bspc config bottom_monocle_padding			-15
bspc config right_monocle_padding			-15
bspc config left_monocle_padding			-15

# Mouse settings
bspc config pointer_modifier				shift
bspc config pointer_action1					move
bspc config pointer_action3					resize_corner

# Monitor settings
bspc config remove_disabled_monitors		true
bspc config remove_unplugged_monitors		true

# Pointer settings
bspc config focus_follows_pointer			true

# Program rules
bspc rule -a Gimp							desktop=^5 follow=on focus=on
bspc rule -a Blender						desktop=^6 follow=on focus=on
bspc rule -a Zathura						state=tiled
