#!/bin/fish

alias h helix
alias ze zellij
alias sudo doas
alias ls 'eza -la --color=auto --group-directories-first'
alias mi 'rate-mirrors artix | doas tee /etc/pacman.d/mirrorlist'
alias up 'yay -Syu'
alias tag 'beet import -i ~/media/music/'
alias vtag 'mnamer -br ~/media/videos/'
alias ev 'qcal -7'
alias vw csvlens

alias cad 'source ~/.local/share/virtual/build123d/bin/activate.fish'
alias vcad 'python -m ocp_vscode --no_tools'

abbr -s st 'stow -vt ~ .'
abbr -a gs 'git status'
abbr -a gp 'git pull'
abbr -a gc 'git checkout'
abbr -a gd 'git diff'
