#!/bin/sh

alias \
	h="helix" \
	ls="eza -la --color=auto --group-directories-first" \
	kh="khal calendar today 30d" \
	up="yay -Syu" \
	tag="beet import -i ~/media/music/"

alias \
	gs="git status" \
	ga="git add" \
	gc="git commit" \
	gp="git push"

alias \
	cad="source ~/.local/share/virtual/build123d/bin/activate" \
	vcad="python -m ocp_vscode --no_tools"
