#!/bin/fish

set -gx EDITOR helix
set -gx TERMINAL footclient
set -gx BROWSER firefox

set -gx XDG_CONFIG_HOME "$HOME/.config"
set -gx XDG_DATA_HOME "$HOME/.local/share"
set -gx XDG_STATE_HOME "$HOME/.local/state"
set -gx XDG_CACHE_HOME "$HOME/.cache"
set -gx XDG_RUNTIME_DIR /run/user/(id -u)

fish_add_path "$XDG_DATA_HOME/npm/bin"
for dir in (find ~/.local/bin -type d)
    fish_add_path "$dir"
end

set -gx GNUPGHOME "$XDG_CONFIG_HOME/gnupg"
set -gx PASSWORD_STORE_DIR "$XDG_DATA_HOME/password-store"
set -gx NOTMUCH_CONFIG "$XDG_CONFIG_HOME/notmuch/notmuchrc"

set -gx NPM_CONFIG_USERCONFIG "$XDG_CONFIG_HOME/npm/npmrc"
set -gx CLAUDE_CONFIG_DIR "$XDG_CONFIG_HOME/claude"
set -gx CARGO_HOME "$XDG_DATA_HOME/cargo"
set -gx GOPATH "$XDG_DATA_HOME/go"
set -gs AWS_PROFILE managed

set -gx LESS RSXcF
set -gx ELECTRON_OZONE_PLATFORM_HINT wayland

if test -z "$WAYLAND_DISPLAY"; and test (tty) = /dev/tty1; and not pidof -q river
    exec river >/dev/null 2>&1
end
