#!/bin/sh

dbus-update-activation-environment \
	SEATD_SOCK \
	WAYLAND_DISPLAY \
	XDG_CURRENT_DESKTOP=hyprland

gsettings set "org.gnome.desktop.interface" color-scheme "prefer-dark"
gsettings set "org.gnome.desktop.interface" gtk-theme "Materia-dark"
gsettings set "org.gnome.desktop.interface" icon-theme "Papirus-Dark"

executes="kanshi waybar foot swaybg wlsunset mpd swayidle rqbit pipewire dunst"
for execute in $executes; do
	pidof -q "$execute" && continue
	case $execute in
	"swaybg") wallpaper & ;;
	"foot") $execute --server & ;;
	"rqbit") $execute server start "$HOME/media/downloads" & ;;
	"wlsunset") $execute -s 21:00 -S 07:00 & ;;
	"swayidle") $execute -w timeout 600 "wlopm --off '*'" \
		resume "wlopm --on '*'" before-sleep "lock" & ;;
	*) $execute & ;;
	esac
done >/dev/null 2>&1
