#!/bin/sh

gsettings set "org.gnome.desktop.interface" gtk-theme "Materia-dark"
gsettings set "org.gnome.desktop.interface" icon-theme "Papirus-Dark"
gsettings set "org.gnome.desktop.interface" cursor-theme "Bibata-Modern-Ice"

dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland

executes="kanshi rivertile waybar foot wlsunset swayidle rqbit mpc mako"
for execute in $executes; do
	pidof -q "$execute" && continue
	case $execute in
	"foot") $execute --server & ;;
	"rivertile") $execute -outer-padding 8 -view-padding 8 -main-ratio 0.55 & ;;
	"rqbit") $execute server start "$HOME/media/downloads" & ;;
	"wlsunset") $execute -s 21:00 -S 07:00 & ;;
	"swayidle") $execute -w \
		timeout 600 "wlopm --off '*'" \
		resume "wlopm --on '*'" & ;;
	"mpc") $execute -q idleloop player | xargs -I{} pkill -RTMIN+1 waybar & ;;
	*) "$execute" & ;;
	esac
done >/dev/null 2>&1
