#!/bin/sh

# A UI for detecting and selecting all displays. Probes autorandr for connected
# displays and lets user select one to use, this takes advantage of the postswitch
# allowing polybar to work well with workspace transitions

singlescreen() {
	xrandr --output "$1" --auto --scale 1.0x1.0 $(echo "$allposs" | grep -v "$1" | awk '{print "--output", $1, "--off"}' | paste -sd ' ')
}

# Checks if External Monitors are available
if [[ $(xrandr -q | grep " connected" | wc -l) -gt 1 ]]; then
	# Get all connected screens.
	screens=$(xrandr -q | grep " connected" | awk '{print $1}')
	# Get user's choice:
	chosen=$(printf "%s\\nDual-Monitors\\nManual Selection" "$screens" | dmenu -i -p "Select Display:")
	case "$chosen" in
		"Manual Selection") arandr; exit ;;
		"Dual-Monitors") autorandr dual ;;
		"eDP-1") autorandr mobile ;;
		"DP-2-1") autorandr docked ;;
		*) singlescreen() "$chosen"
	esac
fi

setbg #Fix background is arragenment has changed
{ killall dunst ; setsid -f dunst ;} >/dev/null 2>&1 # Reset Dunst
