#!/usr/bin/env sh
ifinstalled transmission-remote-cli transmission-cli || exit

[ "$(printf "No\\nYes" | dmenu -i -p "Start transmission daemon?")" = "Yes" ] && transmission-daemon
! pgrep -x transmission-da >/dev/null && transmission-daemon
notify-send "Starting torrent daemon..."

$TERMINAL -e transmission-remote-cli
